add new commands

diff --git a/bin/drop b/bin/drop
--- a/bin/drop
+++ b/bin/drop
@@ -1,10 +1,13 @@
 #!/bin/bash
 
-[[ -d ~/.inventory ]] || mkdir ~/.inventory
-
-if [[ ! -f ~/.inventory/$1 ]]; then
-	echo "you do not have $1"
+if [[ -z $1 ]]; then
+	echo "tell me what to drop"
 	exit 1
 fi
 
-mv ~/.inventory/$1 .
+if [[ ! -f inventory/$1 ]]; then
+	echo "could not find $1 in your inventory"
+	exit 1
+fi
+
+mv ~/inventory/$1 .
